/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
// const baseUrl = config.apiPath.service; // 基础地址
// const testUrl1 = 'http://api-insight.cbg.megvii-inc.com/mock/882';

const baseUrl = config.apiPath.service;

// service path
const urls = {
  deployType: `${baseUrl}/api/kunlun/event/deployTypes:search`, // 查询布控类型
  taskList: `${baseUrl}/api/kunlun/event/deployTasks:searchAll`, // 布控任务列表
  cameraAlbum: `${baseUrl}/api/kunlun/event/historyAlarms/albums`, // 查询底库列表
  clusterList: `${baseUrl}/api/kunlun/event/historyAlarms/data:groupCount`, // 手风琴聚类查询
  alarmList: `${baseUrl}/api/kunlun/event/historyAlarms/data:list`, // 手风琴每一项的列表查询
  fileHistoryAlbumTreeData: `${baseUrl}/api/galaxy/v1/album/list`, // 录像和文件用的底库列表

  exportHistory: `${baseUrl}/api/kunlun/event/historyAlarms/data:export`, // 导出数据
  addTemporaries: `${baseUrl}/api/kunlun/event/temporaries:add`, // 添加到暂存架
  deleteTemporaries: `${baseUrl}/api/kunlun/event/temporaries:delete`, // 移出暂存架
  cameraTree: `${baseUrl}/api/kunlun/event/cameras/tree`, // 相机树接口
  videoTask: `${baseUrl}/api/galaxy/v1/analysis/history/batchTask:list`, // 录像解析任务查询接口
  fileTask: `${baseUrl}/api/galaxy/v1/analysis/offline/batchTask:list`, // 文件解析任务查询接口
  fileListGetter: `${baseUrl}/api/galaxy/v1/analysis/offline/batchTask/item:list`, // 查询子任务列表

};

// service methods
const alarmHistorySrv = {
  getDeployTypeList(params = {}) {
    return MegHttp.httpGet(urls.deployType, params);
  },
  getTaskList(params = {}) {
    return MegHttp.httpGet(urls.taskList, params);
  },
  videoTask(params = {}) {
    return MegHttp.httpPost(urls.videoTask, params);
  },
  fileTask(params = {}) {
    return MegHttp.httpPost(urls.fileTask, params);
  },
  fileListGetter(params = {}) {
    return MegHttp.httpPost(urls.fileListGetter, params);
  },
  cameraTree(params = {}) {
    return MegHttp.httpPost(urls.cameraTree, params);
  },
  getAlbumList(params = {}) {
    return MegHttp.httpPost(urls.cameraAlbum, params);
  },
  getFileHistoryAlbumTreeData(params = {}) {
    return MegHttp.httpPost(urls.fileHistoryAlbumTreeData, params);
  },

  getClusterList(params = {}) {
    return MegHttp.httpPost(urls.clusterList, params, {
      canCancel: true
    });
  },
  exportHistory(params = {}) {
    return MegHttp.httpPost(urls.exportHistory, params);
  },
  getAlarmList(params = {}) {
    return MegHttp.httpPost(urls.alarmList, params);
  },
  addTemporaries(params = {}) {
    return MegHttp.httpPost(urls.addTemporaries, params);
  },
  deleteTemporaries(params = {}) {
    return MegHttp.httpPost(urls.deleteTemporaries, params);
  },
};

export default alarmHistorySrv;
