/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/alarm-history/pages/alarm-history';
import routes from '@/modules/alarm-history/alarm-history.router.js';
import store from '@/modules/alarm-history/store';

export default {
  module,
  routes,
  store: { alarmHistory: store }
};
