/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.galaxyService;
// const authUrl = config.apiPath.auth;

// const menusMockUrl = 'http://api-insight.cbg.megvii-inc.com/mock/654';

// service path
const urls = {
  'taskList': `${baseUrl}/api/galaxy/v1/tasknotice/tasks/list`, // 任务列表
  'taskDelete': `${baseUrl}/api/galaxy/v1/tasknotice/tasks/delete`,
  'taskCanel': `${baseUrl}/api/galaxy/v1/tasknotice/tasks/cancel`,
  'recentTasks': `${baseUrl}/api/galaxy/v1/tasknotice/tasks/recent`, // 最新已完成或者失败的任务
};

// service methods
const LayoutSrv = {
  /**
   * 删除任务
   * @param {*} taskId
   */
  deleteTaskById(taskId = '') {
    return MegHttp.httpPost(`${urls.taskDelete}/${taskId}`);
  },
  /**
   * 终止任务
   * @param {*} taskId
   */
  cancelTaskById(taskId = '') {
    return MegHttp.httpPost(`${urls.taskCanel}/${taskId}`);
  },
  /**
  * 获取最新已确定状态的任务
  */
  getRecentTasks() {
    return MegHttp.httpGet(urls.recentTasks, undefined, { addTTL: true });
  },
  postTaskAction(actionUri) {
    const url = `${baseUrl}${actionUri}`;
    return MegHttp.httpPost(url);
  },
  /**
  * 获取任务列表
  */
  getTaskList() {
    return MegHttp.httpGet(urls.taskList, undefined, { addTTL: true });
  },

};

export default LayoutSrv;
