/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/videotape-analysis/pages/videotape-analysis';
import routes from '@/modules/videotape-analysis/videotape-analysis.router.js';
import store from '@/modules/videotape-analysis/store';

export default {
  module,
  routes,
  store: { videotapeAnalysis: store }
};
