/* Automatically generated by './build/add-module.js' */
import { httpGet, httpPost, httpPatch } from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
// const baseUrl = config.apiPath.service; // 基础地址
const { service: baseUrl, galaxyService: galaxyUrl } = config.apiPath; // 中台服务地址
// const auth = config.apiPath.auth; // auth地址

// service path
const urls = {
  videotapeTaskList: `${baseUrl}/api/kunlun/analysis/history/batchTask:list`, // 录像解析列表检索
  count: `${baseUrl}/api/kunlun/analysis/history/batchTask:stat`, // 统计
  batchDelete: `${baseUrl}/api/kunlun/analysis/history/batchTask:delete`, // 删除
  batchPause: `${baseUrl}/api/kunlun/analysis/history/batchTask:pause`, // 暂停
  batchResume: `${baseUrl}/api/kunlun/analysis/history/batchTask:resume`, // 恢复
  batchTask: `${galaxyUrl}/api/galaxy/v1/analysis/history/batchTask`, // 创建录像解析
  albumList: `${galaxyUrl}/api/galaxy/v1/album/list`, // 底库列表
  editTask: `${galaxyUrl}/api/galaxy/v1/analysis/history/batchTask/`, // 编辑任务
  taskDetail: `${galaxyUrl}/api/galaxy/v1/analysis/history/batchTask/`, // 任务详情
  resumeFailure: `${baseUrl}/api/kunlun/analysis/history/batchTask:resumeFailure`, // 失败重启
  checkName: `${galaxyUrl}/api/galaxy/v1/analysis/history/batchTask/taskName:check`, // 验证任务名称
  cameraStat: `${baseUrl}/api/kunlun/analysis/history/`, // 是否有抓拍和报警
  deviceTree: `${galaxyUrl}/api/galaxy/v1/device/tree`, // 查询相机树
  showTaskErrors: `${galaxyUrl}/api/galaxy/v1/analysis/history/historyTaskError:list`, // 获取录像解析异常列表
};

// service methods
const videotapeAnalysisSrv = {
  showTaskErrors(params) {
    return httpPost(urls.showTaskErrors, params);
  },
  deviceTree(params) {
    return httpPost(urls.deviceTree, params);
  },
  cameraStat(id) {
    return httpGet(`${urls.cameraStat + id}/statistics`);
  },
  /**
   * 底库列表
   */
  albumList() {
    return httpPost(urls.albumList, {
      deployObject: [1, 2, 3, 4, 5],
      type: [2, 3]
    });
  },
  /**
   * 创建录像解析
   */
  batchTask(params) {
    return httpPost(urls.batchTask, params);
  },
  /**
   * 录像解析检索
   */
  getVideotapeTaskList(params = {}) {
    return httpPost(urls.videotapeTaskList, params);
  },
  /**
   * 统计
   */
  getStat(params = {}) {
    return httpPost(urls.count, params);
  },
  /**
   * 批量删除
   */
  batchDelete(params = {}) {
    return httpPost(urls.batchDelete, params);
  },
  /**
   * 批量暂停
   */
  batchPause(params = {}) {
    return httpPost(urls.batchPause, params);
  },
  /**
   * 批量恢复
   */
  batchResume(params = {}) {
    return httpPost(urls.batchResume, params);
  },
  /**
   * 编辑任务
   */
  editTask(id, params) {
    return httpPatch(urls.editTask + id, params);
  },
  /**
   * 任务详情
   */
  taskDetail(id, params) {
    return httpGet(urls.taskDetail + id, params);
  },
  /**
   * 失败重启
   */
  resumeFailure(params) {
    return httpPost(urls.resumeFailure, params);
  },
  /**
   * 验证任务名称是否重复
   */
  checkName(params) {
    return httpPost(`${urls.checkName}?taskName=${params.taskName}`);
  }
};

export default videotapeAnalysisSrv;
