/* eslint-disable consistent-return */
/* Automatically generated by './build/add-module.js' */
export default [{
  children: [
    {
      path: 'detail',
      name: 'detail',
      component: () => import(/* webpackChunkName: "detail" */'./pages/detail')
    }
  ]
}];
