/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/collision/pages/collision';
import routes from '@/modules/collision/collision.router.js';
import store from '@/modules/collision/store';

export default {
  module,
  routes,
  store: { collision: store }
};
