/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/shelf-track-analysis/pages/shelf-track-analysis';
import routes from '@/modules/shelf-track-analysis/shelf-track-analysis.router.js';
import store from '@/modules/shelf-track-analysis/store';

export default {
  module,
  routes,
  store: { shelfTrackAnalysis: store }
};
