/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址

// service path
const urls = {
  'searchTrack': `${baseUrl}/api/kunlun/event/temporaries/track:searchAll`,
  'captureSearchTrack': `${baseUrl}/api/kunlun/search/capture/track:searchAll`,
  'cascadeCaptureSearchTrack': `${baseUrl}/api/kunlun/search/cascade/capture/track:searchAll`,
};
// service methods
const trackSrv = {
  /**
   * 轨迹列表
   */
  searchTrack(params) {
    return MegHttp.httpPost(urls.searchTrack, params);
  },
  /**
   * 轨迹列表 - 抓拍
   */
  captureSearchTrack(params) {
    return MegHttp.httpPost(urls.captureSearchTrack, params);
  },
  /**
   * 轨迹列表 - 级联抓拍
   */
  cascadeCaptureSearchTrack(params) {
    return MegHttp.httpPost(urls.cascadeCaptureSearchTrack, params);
  },
};
export default trackSrv;
