/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
// const baseUrl = config.apiPath.service; // 基础地址
const galaxyUrl = config.apiPath.galaxyService; // 中台服务地址
// const auth = config.apiPath.auth; // auth地址

// service path
const urls = {
  analysisDetail: `${galaxyUrl}/api/galaxy/v1/analysis/offline/batchTask`, // 解析任务详情
  detailFileList: `${galaxyUrl}/api/galaxy/v1/analysis/offline/batchTask/item:list`, // 解析任务文件列表
  editTask: `${galaxyUrl}/api/galaxy/v1/analysis/offline/batchTask`, // 编辑任务
};

// service methods
const analysisDetailSrv = {
  // 编辑任务
  editTask(id, params) {
    return MegHttp.httpPatch(`${urls.editTask}/${id}`, params);
  },
  // 查询任务详情
  getAnalysisDetail(params = {}) {
    return MegHttp.httpGet(`${urls.analysisDetail}/${params.id}`);
  },
  // 查询文件列表
  getDetailFileList(params = {}) {
    return MegHttp.httpPost(urls.detailFileList, params);
  },
};

export default analysisDetailSrv;
