/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/file-analysis/pages/file-analysis';
import routes from '@/modules/file-analysis/file-analysis.router.js';
import store from '@/modules/file-analysis/store';

export default {
  module,
  routes,
  store: { fileAnalysis: store }
};
