/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
const galaxyUrl = config.apiPath.galaxyService; // 中台服务地址
// const auth = config.apiPath.auth; // auth地址

// service path
const urls = {
  fileAnalysisList: `${galaxyUrl}/api/galaxy/v1/analysis/offline/batchTask:list`, // 解析服务资源监控
  resourceMonitor: `${galaxyUrl}/api/galaxy/v1/analysis/resource/monitor`, // 解析服务资源监控
  albumList: `${galaxyUrl}/api/galaxy/v1/album/list`, // 底库列表
  pathList: `${baseUrl}/api/galaxy/v1/file/files:paths`, // 文件夹列表
  fileList: `${baseUrl}/api/kunlun/analysis/offline/files`, // 未创建解析任务的文件列表
  counts: `${baseUrl}/api/galaxy/v1/file/files:count`, // 文件个数统计
  creatAnalysisTask: `${galaxyUrl}/api/kunlun/analysis/offline`, // 创建文件解析任务
  analysisDetail: `${galaxyUrl}/api/galaxy/v1/analysis/offline/batchTask`, // 解析任务详情
  editTask: `${galaxyUrl}/api/galaxy/v1/analysis/offline/batchTask`, // 编辑任务
  deleteTask: `${galaxyUrl}/api/galaxy/v1/analysis/offline/batchTask:delete`, // 删除任务
  pauseTask: `${galaxyUrl}/api/galaxy/v1/analysis/offline/batchTask:pause`, // 暂停任务
  resumeTask: `${galaxyUrl}/api/galaxy/v1/analysis/offline/batchTask:resume`, // 失败任务重新分析
  restartTask: `${galaxyUrl}/api/galaxy/v1/analysis/offline/batchTask:restart`, // 继续文件解析任务
  taskStatusStatistics: `${galaxyUrl}/api/galaxy/v1/analysis/offline/batchTask:stat`, // 文件主任务列表统计
  photoUploadAnalyze: `${galaxyUrl}/api/galaxy/v1/album/task:photoUploadAnalyze`, // 图片上传任务解析
};

// service methods
const fileAnalysisSrv = {
  /**
   * 文件解析任务状态统计
   */
  uploadAnalyzePhoto(params = {}) {
    return MegHttp.httpPost(urls.photoUploadAnalyze, params);
  },
  /**
   * 文件解析任务状态统计
   */
  getTaskStatusStatistics(params = {}) {
    return MegHttp.httpPost(urls.taskStatusStatistics, params);
  },
  /**
   * 重启文件解析任务
   */
  restartTask(params = {}) {
    return MegHttp.httpPost(urls.restartTask, params);
  },
  /**
   * 失败任务重新分析
   */
  resumeTask(params = {}) {
    return MegHttp.httpPost(urls.resumeTask, params);
  },
  /**
   * 暂停文件解析任务
   */
  pauseTask(params = {}) {
    return MegHttp.httpPost(urls.pauseTask, params);
  },
  /**
   * 删除文件解析任务
   */
  deleteTask(params = {}) {
    return MegHttp.httpPost(urls.deleteTask, params);
  },
  // 编辑任务
  editTask(id, params) {
    return MegHttp.httpPatch(`${urls.editTask}/${id}`, params);
  },
  // 查询任务详情
  getAnalysisDetail(params = {}) {
    return MegHttp.httpGet(`${urls.analysisDetail}/${params.id}`);
  },
  /**
   * 创建文件解析任务
   */
  creatAnalysisTask(params = {}) {
    return MegHttp.httpPost(urls.creatAnalysisTask, params);
  },
  // 查询文件个数
  queryCounts(params = {}) {
    return MegHttp.httpGet(urls.counts, params);
  },
  // 中台获取文件夹列表
  getPathList(params = {}) {
    return MegHttp.httpGet(urls.pathList, params);
  },
  /**
   * 底库列表
   */
  albumList(params = {}) {
    return MegHttp.httpPost(urls.albumList, params);
  },
  /**
   * 获取解析资源数据
   */
  getLastResouce(params = {}) {
    return MegHttp.httpGet(urls.resourceMonitor, params);
  },
  /**
   * @description 中台根据parentId获取文件列表
   */
  getFileList(params = {}) {
    return MegHttp.httpPost(urls.fileList, params);
  },
  /**
   * 取消收藏该条目
   */
  getFileAnalysisList(params = {}) {
    return MegHttp.httpPost(urls.fileAnalysisList, params);
  },
};

export default fileAnalysisSrv;
