/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
const galaxyUrl = config.apiPath.galaxyService;

// service path
const urls = {
  traceSearchPath: `${baseUrl}/api/kunlun/judge/orbit/track:queryAll`,
  monitorPath: `${baseUrl}/api/galaxy/v1/analysis/resource/monitor`,
  historyBatchTaskPath: `${baseUrl}/api/galaxy/v1/analysis/history/batchTask:stat`,
  realtimePath: `${baseUrl}/api/kunlun/analysis/realtime/statistics`,
  fileBatchTaskPath: `${baseUrl}/api/galaxy/v1/analysis/offline/batchTask:stat`,
  whetherAnalysisRealtimePath: `${baseUrl}/api/kunlun/analysis/realtime/orbit:noAnalysisIds`,
  whetherAnalysisHistoryPath: `${baseUrl}/api/galaxy/v1/analysis/history/camera/unanalysis:list`,
  joinEventPath: `${baseUrl}/api/kunlun/event/events/{id}/clues`,
  newCreateEvent: `${baseUrl}/api/kunlun/event/events`,
  getEventListPath: `${baseUrl}/api/kunlun/event/events:search`,
  addEventThreadPath: `${baseUrl}/api/kunlun/event/events/`,
  searchCluesPath: `${baseUrl}/api/kunlun/event/clues:searchAll`,
  cameraList: `${baseUrl}/api/galaxy/v1/device/tree`, // 获取有权限的相机列表
  getBatchTaskPath: `${baseUrl}/api/galaxy/v1/analysis/history/batchTask:list`,
  pauseRealtimePath: `${baseUrl}/api/kunlun/analysis/realtime/batchPause`,
  resumeRealtimePath: `${baseUrl}/api/kunlun/analysis/realtime/batchResume`,
  createBatchTask: `${baseUrl}/api/galaxy/v1/analysis/history/batchTask`,
  export: `${baseUrl}/api/kunlun/judge/orbit/export`,
  batchTaskResume: `${baseUrl}/api/galaxy/v1/analysis/history/batchTask:resume`,
  batchTaskPause: `${baseUrl}/api/galaxy/v1/analysis/history/batchTask:pause`,
  realtimeList: `${baseUrl}/api/galaxy/v1/analysis/realtime/list`,
  cameraMsg: `${baseUrl}/api/galaxy/v1/device/cameras/`,
  captureCount: `${galaxyUrl}/api/galaxy/v1/capture/dashboard/count`, // 查询抓拍数
  labels: `${galaxyUrl}/api/galaxy/v1/device/cameras:labels`, // 查询相机标签
};

// service methods
const pathTraceSrv = {
  traceSearch(params = {}) {
    return MegHttp.httpPost(urls.traceSearchPath, params);
  },
  monitorRate(params = {}) {
    return MegHttp.httpGet(urls.monitorPath, params);
  },
  historyBatchTask(params = {}) {
    return MegHttp.httpPost(urls.historyBatchTaskPath, params);
  },
  realtime(params = {}) {
    return MegHttp.httpPost(urls.realtimePath, params);
  },
  fileBatchTask(params = {}) {
    return MegHttp.httpPost(urls.fileBatchTaskPath, params);
  },
  whetherAnalysisRealtime(params = {}) {
    return MegHttp.httpPost(urls.whetherAnalysisRealtimePath, params);
  },
  whetherAnalysisHistory(params = {}) {
    return MegHttp.httpPost(urls.whetherAnalysisHistoryPath, params);
  },
  joinEventPath(params = {}) {
    return MegHttp.httpPost(urls.joinEventPath, params);
  },
  newCreateEvent(params = {}) {
    return MegHttp.httpPost(urls.newCreateEvent, params);
  },
  getEventList(params = {}) {
    return MegHttp.httpPost(urls.getEventListPath, params);
  },
  addEventThread(params = {}) {
    return MegHttp.httpPost(`${urls.addEventThreadPath}${params.id}/clues`, { clueList: params.clueList });
  },
  searchClues(params = {}) {
    return MegHttp.httpPost(urls.searchCluesPath, params);
  },
  getBatchTask(params = {}) {
    return MegHttp.httpPost(urls.getBatchTaskPath, params);
  },
  getRealtimeList(params = {}) {
    return MegHttp.httpPost(urls.realtimeList, params);
  },
  /**
  * 获取有权限的相机列表
   */
  cameraList(params = {}) {
    return MegHttp.httpPost(urls.cameraList, params);
  },
  pauseRealtime(params = {}) {
    return MegHttp.httpPost(urls.pauseRealtimePath, params);
  },
  resumeRealtime(params = {}) {
    return MegHttp.httpPost(urls.resumeRealtimePath, params);
  },
  /**
   * @description 创建录像解析
   */
  createBatchTask(params = {}) {
    return MegHttp.httpPost(urls.createBatchTask, params);
  },
  /**
   * @description 导出
   */
  export(params = {}) {
    return MegHttp.httpPost(urls.export, params);
  },
  // 恢复
  batchTaskResume(params = {}) {
    return MegHttp.httpPost(urls.batchTaskResume, params);
  },
  // 暂停
  batchTaskPause(params = {}) {
    return MegHttp.httpPost(urls.batchTaskPause, params);
  },
  cameraMsg(params = {}) {
    return MegHttp.httpPost(urls.cameraMsg + params.id);
  },
  /**
    * 查询相机标签
    */
  getLabels(request = {}) {
    return MegHttp.httpGet(urls.labels, request);
  },
  /**
   * 查询抓拍数
   */
  getCaptureCount(request = {}) {
    return MegHttp.httpPost(urls.captureCount, request);
  },
};

export default pathTraceSrv;
