/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/open-api/pages/open-api';
import routes from '@/modules/open-api/open-api.router.js';
import store from '@/modules/open-api/store';

export default {
  module,
  routes,
  store: { openApi: store },
};
