/* Automatically generated by './build/add-module.js' */
import actions from './actions';
import mutations from './mutations';
import getters from './getters';

const quickNavigation = {
  namespaced: true,
  mutations,
  actions,
  getters,
  state: {
    userModules: null,
    userTechniques: null,
    userModulesOrigin: null,
    userTechniquesOrigin: null
  },
};

export default quickNavigation;
