/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service;
// const authUrl = config.apiPath.auth;

// http://api-insight.cbg.megvii-inc.com/project/1684/interface/api/142502

// service path
const urls = {
  'shelfList': `${baseUrl}/api/kunlun/event/temporaries:search`, // 暂存架列表
  'addShelf': `${baseUrl}/api/kunlun/event/temporarys`, // 添加到暂存架
  'export': `${baseUrl}/api/kunlun/event/temporaries:export`, // 导出
  'delete': `${baseUrl}/api/kunlun/event/temporaries:delete`, // 删除
  'getCount': `${baseUrl}/api/kunlun/event/temporaries:count`, // 暂存架数量统计
  'eventList': `${baseUrl}/api/kunlun/event/events:searchAll`, // 事件列表
  'addToClues': (id) => `${baseUrl}/api/kunlun/event/events/${id}/clues`, // 事件列表
  'addToIdentity': (id) => `${baseUrl}/api/kunlun/event/events/${id}/identitys`// 添加到关联身份
};

// service methods
const ShelfSrv = {
  /**
   * 暂存架列表
   */
  getShelfList(params) {
    return MegHttp.httpPost(urls.shelfList, params);
  },
  /*
  * 添加到暂存架
  * @param {params}: 参数
  * @return
  * */
  addToShelf(params) {
    return MegHttp.httpPost(urls.addShelf, params);
  },
  /*
  * 删除暂存架
  * @param {any}
  * @return
  * */
  deleteShelf(params) {
    return MegHttp.httpPost(urls.delete, params);
  },
  /*
  * 导出暂存架
  * @param {params}: 参数
  * @return
  * */
  exportShelf(params) {
    return MegHttp.httpPost(urls.export, params);
  },
  /*
  * 暂存架数量统计
  * @param {any}
  * @return
  * */
  getCount() {
    return MegHttp.httpGet(urls.getCount);
  },
  /*
  * 获取事件列表
  * @param {any}
  * @return
  * */
  getEventList() {
    return MegHttp.httpGet(urls.eventList);
  },
  /*
  * 添加到线索库
  * @param {any}
  * @return
  * */
  addToClues(params) {
    const { id } = params;
    delete params.id;
    return MegHttp.httpPost(urls.addToClues(id), params);
  },
  /*
  * 添加到关联身份
  * @param {any}
  * @return
  * */
  addToIdentity(params) {
    const { id } = params;
    delete params.id;
    return MegHttp.httpPost(urls.addToIdentity(id), params);
  }
};

export default ShelfSrv;
