/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/guide/pages/guide';
import routes from '@/modules/guide/guide.router.js';
import store from '@/modules/guide/store';

export default {
  module,
  routes,
  store: { guide: store }
};
