/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/intelligent-box/pages/intelligent-box';
import routes from '@/modules/intelligent-box/intelligent-box.router';

export default {
  module,
  routes,
};
