/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/peer/pages/peer';
import routes from '@/modules/peer/peer.router.js';
import store from '@/modules/peer/store';

export default {
  module,
  routes,
  store: { peer: store }
};
