/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const auth = window.config.globalConfig.apiPath.auth; // auth地址

// service path
const urls = {
  'peerList': `${baseUrl}/api/kunlun/judge/companion/list`,
  'peerStatistics': `${baseUrl}/api/kunlun/judge/companion/statistics`,
  'taskDetail': `${baseUrl}/api/kunlun/judge/companion/resultList/`,
  'personResult': `${baseUrl}/api/kunlun/judge/companion/personResult/`,
  'addTask': `${baseUrl}/api/kunlun/judge/companion/add`, // 添加任务
  'deleteTask': `${baseUrl}/api/kunlun/judge/companion/del/`, // 删除任务
  'deleteResult': `${baseUrl}/api/kunlun/judge/companion/delResult`, // 删除单个结果
  'cancelTask': `${baseUrl}/api/kunlun/judge/companion/cancel/`, // 取消任务
  'restartTask': `${baseUrl}/api/kunlun/judge/companion/restart/`, // 重新开始任务
  'jobDetail': `${baseUrl}/api/kunlun/judge/companion/`, // 任务信息
  'taskName': `${baseUrl}/api/kunlun/judge/companion/nameExist`, // 任务名是否存在
  'modifyJobName': `${baseUrl}/api/kunlun/judge/companion/modifyJobName/`, // 修改任务名
  'export': `${baseUrl}/api/kunlun/judge/companion/export`, // 导出
  'searchByPhotos': `${baseUrl}/api/kunlun/search/capture/allInOne/queryCaptureResult`, // 以图搜图
};

// service methods
const PeerSrv = {
  /**
 * 新建任务
 */
  addTask(params = {}) {
    return MegHttp.httpPost(urls.addTask, params);
  },
  // 删除任务
  deleteTask(params = '') {
    return MegHttp.httpGet(urls.deleteTask + params);
  },
  // 取消任务
  cancelTask(params = '') {
    return MegHttp.httpPost(urls.cancelTask + params);
  },
  // 重新开始任务
  restartTask(params = '') {
    return MegHttp.httpPost(urls.restartTask + params);
  },
  // 删除单个结果
  deleteResult(params = {}) {
    return MegHttp.httpGet(urls.deleteResult, params);
  },
  // 频繁出没列表
  getPeerList(params = {}) {
    return MegHttp.httpGet(urls.peerList, params);
  },
  // 进度统计
  peerStatistics(params = {}) {
    return MegHttp.httpGet(urls.peerStatistics, params);
  },
  // 任务详情
  taskDetail(params = '') {
    return MegHttp.httpGet(urls.taskDetail + params);
  },
  // 任务人员出现记录
  personResult(params = {}) {
    return MegHttp.httpGet(urls.personResult + params.personId, { groupType: params.groupType });
  },
  // 任务详情
  jobDetail(params = '') {
    return MegHttp.httpGet(urls.jobDetail + params);
  },
  // 任务名是否存在
  taskName(params = {}) {
    return MegHttp.httpGet(urls.taskName, params);
  },
  // 修改任务名
  modifyJobName(params = {}) {
    return MegHttp.httpPost(urls.modifyJobName + params.jobId, { jobName: params.jobName });
  },
  // 导出
  export(params = {}) {
    return MegHttp.httpPost(urls.export, params);
  },
  searchByPhotos(params = {}) {
    return MegHttp.httpPost(urls.searchByPhotos, params);
  },
};

export default PeerSrv;
