/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/multiple-search/pages/multiple-search';
import routes from '@/modules/multiple-search/multiple-search.router.js';
import store from '@/modules/multiple-search/store';

export default {
  module,
  routes,
  store: { multipleSearch: store }
};
