/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const auth = config.apiPath.auth; // auth地址

// service path
const urls = {
  'allJudgesAfter': `${baseUrl}/api/kunlun/judge/publicTechnical`, // 全部事后研判（含用户自定义技战法）
  'getLabelList': `${baseUrl}/api/galaxy/v1/profile/label/list`, // (中台)自定义标签列表
  'getAreaList': `${baseUrl}/api/kunlun/areas/tree`, // 获取区域列表
  'getTacticLabelList': `${baseUrl}/api/kunlun/setup/tactic/label/list`, //  战法标签
};

// service methods
const multipleSearchSrv = {
  /**
   * 获取全部的时候研判包括用户自定义技战法
   */
  getAllJudgesAfter(params) {
    return MegHttp.httpPost(urls.allJudgesAfter, params);
  },
  /**
   * 获取标签列表
   */
  getLabelList(params) {
    return MegHttp.httpPost(urls.getLabelList, params);
  },
  /**
   * 获取区域列表
   */
  getAreaList(params) {
    return MegHttp.httpGet(urls.getAreaList, params);
  },
  /**
   * 战法标签
   */
  getTacticLabelList(params) {
    return MegHttp.httpGet(urls.getTacticLabelList, params);
  },

};

export default multipleSearchSrv;
