/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const auth = config.apiPath.auth; // auth地址

// service path
const urls = {
  statistics: `${baseUrl}/api/kunlun/statistic/capture/dashBoard:stat`,
  heat: `${baseUrl}/api/kunlun/statistic/capture/heatMap:stat`,
  property: `${baseUrl}/api/kunlun/statistic/capture/property:stat`,
  attribute: `${baseUrl}/api/galaxy/v1/system/deploy/dic/search`,
  heatMapExport: `${baseUrl}/api/kunlun/statistic/capture/heatMap:export`,
  attrExport: `${baseUrl}/api/kunlun/statistic/capture/property:export`,
  dashBoardExport: `${baseUrl}/api/kunlun/statistic/capture/dashBoard:export`
};

// service methods
const captureStatisticsSrv = {
  /**
   * 属性统计导出
   */
  getAttrExport(params) {
    return MegHttp.httpPost(urls.attrExport, params);
  },
  /**
   * 热力图导出
   */
  getHeatMapExport(params) {
    return MegHttp.httpPost(urls.heatMapExport, params);
  },
  /**
   * 态势页导出
   */
  getDashBoardExport(params) {
    return MegHttp.httpPost(urls.dashBoardExport, params);
  },
  /**
   * 态势页数据
   */
  getStatisticsData(params) {
    return MegHttp.httpPost(urls.statistics, params, {
      transformParams: false
    });
  },
  /**
   *
   * 热力图页数据
   *
   */
  getHeatData(params) {
    return MegHttp.httpPost(urls.heat, params, {
      transformParams: false
    });
  },
  /**
   * 布控属性列表
   *
   */
  getAttributeList(params) {
    return MegHttp.httpGet(urls.attribute, params);
  },
  /**
   * 属性页数据
   *
   */
  getAttributeData(params) {
    return MegHttp.httpPost(urls.property, params, {
      transformParams: false
    });
  },

};

export default captureStatisticsSrv;
