/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/capture-statistics/pages/capture-statistics';
import routes from '@/modules/capture-statistics/capture-statistics.router.js';
import store from '@/modules/capture-statistics/store';

export default {
  module,
  routes,
  store: { captureStatistics: store }
};
