/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/alarm-realtime/pages/alarm-realtime';
import routes from '@/modules/alarm-realtime/alarm-realtime.router.js';
import store from '@/modules/alarm-realtime/store';

export default {
  module,
  routes,
  store: { alarmRealtime: store }
};
