/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/cascade-capture-search/pages/cascade-capture-search';
import routes from '@/modules/cascade-capture-search/cascade-capture-search.router.js';
import store from '@/modules/cascade-capture-search/store';

export default {
  module,
  routes,
  store: { cascadeCaptureSearch: store }
};
