/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const huixunUrl = process.env.NODE_ENV === 'development' ? 'http://api-insight.cbg.megvii-inc.com/mock/1642' : baseUrl;
// const { auth } = config.apiPath; // auth地址

// service path
const urls = {
  dashboard: `${baseUrl}/api/kunlun/statistic/dashBoard:stat`,
  situationTop10: `${baseUrl}/api/kunlun/areas/situation/scoreTop`,
  // 团伙人员关注指数
  situationActive10: `${baseUrl}/api/kunlun/situation/active:top20`,
  situationOverview: `${baseUrl}/api/kunlun/situation`,
  // 关注人员统计
  situationFocus: `${baseUrl}/api/kunlun/situation/stats/focus`,
  // 关注人员数量统计基于点位
  focusMap: `${baseUrl}/api/kunlun/situation/tactic/focus/count/camera`,
  // 防控单元态势
  areasSituation: `${baseUrl}/api/kunlun/areas/situation`,
  // 抓怕态势
  captureMap: `${baseUrl}/api/kunlun/statistic/dashBoard:capture`,
  // 报警态势
  alarmMap: `${baseUrl}/api/kunlun/statistic/dashBoard:warning`,
  // 关注人员统计
  tacticFocusCount: `${baseUrl}/api/kunlun/situation/tactic/focus/count/`,
  // 战法-数量统计
  tacticsCount: `${baseUrl}/api/kunlun/setup/tactic/count`
};

// service methods
/**
 * 获取dashboard数据
 */
const dashboardSrv = {
  // 获取dashboard数据
  getDashboardData(params = {}) {
    return MegHttp.httpPost(urls.dashboard, params);
  },
  getSituationTop10() {
    return MegHttp.httpPost(urls.situationTop10);
  },
  getSituationActive10() {
    return MegHttp.httpGet(urls.situationActive10);
  },
  // 获取防控单元，关注网格，挖掘团伙数据
  getSituationOverview() {
    return MegHttp.httpGet(urls.situationOverview);
  },
  // 管控人员统计
  getSituationFocus() {
    return MegHttp.httpGet(urls.situationFocus);
  },
  // 获取关注人员数据
  getFocusMap() {
    return MegHttp.httpPost(urls.focusMap);
  },
  // 获取防控单元态势-区域地图概览
  getAreasSituationMap() {
    return MegHttp.httpGet(urls.areasSituation);
  },
  // 抓拍态势
  getCaptureMap() {
    return MegHttp.httpPost(urls.captureMap);
  },
  // 报警态势
  getAlarmMap() {
    return MegHttp.httpPost(urls.alarmMap);
  },
  // 关注人员统计
  getTacticFocusCount() {
    return MegHttp.httpGet(urls.tacticFocusCount);
  },
  // 战法统计
  getTacticCount() {
    return MegHttp.httpGet(urls.tacticsCount);
  }
};

export default dashboardSrv;
