/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/dashboard/pages/dashboard';
import routes from '@/modules/dashboard/dashboard.router.js';
import store from '@/modules/dashboard/store';

export default {
  module,
  routes,
  store: { dashboard: store }
};
