/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/cascade-alarm-history/pages/cascade-alarm-history';
import routes from '@/modules/cascade-alarm-history/cascade-alarm-history.router.js';
import store from '@/modules/cascade-alarm-history/store';

export default {
  module,
  routes,
  store: { cascadeAlarmHistory: store }
};
