/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const auth = config.apiPath.auth; // auth地址

// service path
const urls = {
  statistics: `${baseUrl}/api/kunlun/statistic/warning/dashBoard:stat`,
  heat: `${baseUrl}/api/kunlun/statistic/warning/heatMap:stat`,
  deployType: `${baseUrl}/api/kunlun/event/deployTypes:search`,
  database: `${baseUrl}/api/kunlun/event/historyAlarms/albums`,
  databaseStatistics: `${baseUrl}/api/kunlun/statistic/warning/album:stat`,
  heatExport: `${baseUrl}/api/kunlun/statistic/warning/heatMap:export`,
  dashBoardExport: `${baseUrl}/api/kunlun/statistic/warning/dashBoard:export`,
};

// service methods
const alarmStatisticsSrv = {
  getHeatExport(params) {
    return MegHttp.httpPost(urls.heatExport, params);
  },
  getDashBoardExport(params) {
    return MegHttp.httpPost(urls.dashBoardExport, params);
  },
  getStatisticsData(params) {
    return MegHttp.httpPost(urls.statistics, params, {
      transformParams: false
    });
  },
  getHeatData(params) {
    return MegHttp.httpPost(urls.heat, params, {
      transformParams: false
    });
  },
  getDeployType(params) {
    return MegHttp.httpGet(urls.deployType, params);
  },
  getDatabaseData(params = {}) {
    return MegHttp.httpPost(urls.database, params);
  },
  getDatabaseStatistics(params) {
    return MegHttp.httpPost(urls.databaseStatistics, params, {
      transformParams: false
    });
  }
};

export default alarmStatisticsSrv;
