/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/alarm-statistics/pages/alarm-statistics';
import routes from '@/modules/alarm-statistics/alarm-statistics.router.js';
import store from '@/modules/alarm-statistics/store';

export default {
  module,
  routes,
  store: { alarmStatistics: store }
};
