/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';
// path prefix
const baseUrl = config.apiPath.galaxyService;
// const authUrl = window.config.globalConfig.apiPath.auth;
// const baseUrl = 'http://api-insight.cbg.megvii-inc.com/mock/1638';
// ``
// service path background: url('./images/body-bg.png')
const urls = {
  'analyze': `${baseUrl}/api/galaxy/v1/system/image/action/image:analyze`, // 多人脸识别
  'getRecentPhotos': `${baseUrl}/api/galaxy/v1/recent/recentPhotos`, // 获取最近上传的图片列表
};

const ImgAnalysisSrv = {
  /**
   * 多人脸识别
   */
  getAnalyze(params = {}) {
    return MegHttp.httpPost(urls.analyze, params);
  },
  /**
   * 获取最近上传的图片列表
   */
  getRecentPhotos(params = {}) {
    return MegHttp.httpGet(urls.getRecentPhotos, params);
  },
};
export default ImgAnalysisSrv;
