/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/region/pages/region';
import routes from '@/modules/region/region.router.js';
import store from '@/modules/region/store';

export default {
  module,
  routes,
  store: { region: store }
};
