/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const auth = window.config.globalConfig.apiPath.auth; // auth地址

// service path
const urls = {
  'regionList': `${baseUrl}/api/kunlun/judge/regionCollision/jobList`,
  'regionStatistics': `${baseUrl}/api/kunlun/judge/regionCollision/progress/statistics`,
  'taskDetail': `${baseUrl}/api/kunlun/judge/regionCollision/resultList/`,
  'personResult': `${baseUrl}/api/kunlun/judge/regionCollision/personResultGroup/`,
  'cameraList': `${baseUrl}/api/galaxy/v1/device/tree`, // 获取有权限的相机列表
  'addTask': `${baseUrl}/api/kunlun/judge/regionCollision/add`, // 添加任务
  'deleteTask': `${baseUrl}/api/kunlun/judge/regionCollision/delete/`, // 删除任务
  'deleteResult': `${baseUrl}/api/kunlun/judge/regionCollision/delResult`, // 删除单个结果
  'jobDetail': `${baseUrl}/api/kunlun/judge/regionCollision/detail/`, // 任务信息
  'taskName': `${baseUrl}/api/kunlun/judge/regionCollision/nameExist/`, // 人物名是否存在
  'threshold': `${baseUrl}/api/kunlun/judge/regionCollision/threshold`, // 获取推荐阈值
  'regionCancel': `${baseUrl}/api/kunlun/judge/regionCollision/cancel/`, // 终止任务
  'restartTask': `${baseUrl}/api/kunlun/judge/regionCollision/restart/`, // 重新开始任务
  'modifyJobName': `${baseUrl}/api/kunlun/judge/regionCollision/modifyJobName/`, // 修改任务名
  'export': `${baseUrl}/api/kunlun/judge/regionCollision/export`, // 导出
};

// service methods
const RegionSrv = {
  /**
   * 新建任务
   */
  addTask(params = {}) {
    return MegHttp.httpPost(urls.addTask, params);
  },
  // 删除任务
  deleteTask(params = '') {
    return MegHttp.httpPost(urls.deleteTask + params);
  },
  // 删除单个结果
  deleteResult(params = {}) {
    return MegHttp.httpGet(urls.deleteResult, params);
  },
  // 频繁出没列表
  getRegionList(params = {}) {
    return MegHttp.httpGet(urls.regionList, params);
  },
  // 进度统计
  regionStatistics(params = {}) {
    return MegHttp.httpGet(urls.regionStatistics, params);
  },
  // 任务详情
  taskDetail(params = '') {
    return MegHttp.httpGet(urls.taskDetail + params);
  },
  // 任务人员出现记录
  personResult(params = {}) {
    return MegHttp.httpGet(urls.personResult + params.personId, { groupType: params.groupType });
  },
  /**
  * 获取有权限的相机列表
   */
  cameraList(params = {}) {
    return MegHttp.httpPost(urls.cameraList, params);
  },
  // 任务详情
  jobDetail(params = '') {
    return MegHttp.httpGet(urls.jobDetail + params);
  },
  // 任务名是否存在
  taskName(params = {}) {
    return MegHttp.httpGet(urls.taskName, params);
  },
  threshold(params = {}) {
    return MegHttp.httpGet(urls.threshold, params);
  },
  regionCancel(params = '') {
    return MegHttp.httpPost(urls.regionCancel + params);
  },
  restartTask(params = '') {
    return MegHttp.httpPost(urls.restartTask + params);
  },
  // 修改任务名
  modifyJobName(params = {}) {
    return MegHttp.httpPost(urls.modifyJobName + params.id, { jobName: params.jobName });
  },
  // 导出
  export(params = {}) {
    return MegHttp.httpPost(urls.export, params);
  },
};

export default RegionSrv;
