/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const auth = config.apiPath.auth; // auth地址
const galaxyUrl = config.apiPath.galaxyService; // 中台服务地址

// service path
const urls = {
  aggCapture: `${baseUrl}/api/kunlun/search/capture/{type}/aggCapture`, // 聚合结果
  queryCapture: `${baseUrl}/api/kunlun/search/capture/{type}/queryCapture`, // 抓拍结果
  batchExport: `${galaxyUrl}/api/galaxy/v1/capture/{type}/batch:exportCapture`, // 批量导出
  export: `${galaxyUrl}/api/galaxy/v1/capture/{type}/several:exportCapture`, // 导出多条抓拍结果
};

// service methods
const captureSearchSrv = {
  // 查询抓拍列表
  queryCapture(params = {}) {
    // allInOne property
    return MegHttp.httpPost(urls.queryCapture.replace(/{type}/, params.type || 'allInOne'), params, { canCancel: true });
  },
  // 聚合接口
  aggCapture(params = {}) {
    return MegHttp.httpPost(urls.aggCapture.replace(/{type}/, params.type || 'allInOne'), params, { canCancel: true });
  },
  // 批量导出
  batchExport(params = {}) {
    return MegHttp.httpPost(urls.batchExport.replace(/{type}/, params.type || 'allInOne'), params);
  },
  // 导出多条抓拍结果
  export(params = {}) {
    return MegHttp.httpPost(urls.export.replace(/{type}/, params.type || 'allInOne'), params);
  },
};

export default captureSearchSrv;
