/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/capture-search/pages/capture-search';
import routes from '@/modules/capture-search/capture-search.router.js';
import store from '@/modules/capture-search/store';

export default {
  module,
  routes,
  store: { captureSearch: store }
};
