/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/surveillance-task/pages/surveillance-task';
import routes from '@/modules/surveillance-task/surveillance-task.router.js';
import store from '@/modules/surveillance-task/store';

export default {
  module,
  routes,
  store: { surveillanceTask: store }
};
