/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service;
// const testUrl1 = 'http://api-insight.cbg.megvii-inc.com/mock/1488';
const galaxy = config.apiPath.galaxyService; // 中台
// service path
const urls = {
  surveillanceTaskList: `${baseUrl}/api/kunlun/event/deployTasks:search`, // 布控任务列表
  deployType: `${baseUrl}/api/kunlun/event/deployTypes:search`, // 查询布控类型
  cameraAlbum: `${baseUrl}/api/kunlun/event/cameraAlbums:search`, // 查询相机和底库列表,即可差全部，也可以查某布控任务所属
  updateStatus: (id) => `${baseUrl}/api/kunlun/event/deployTasks/${id}:updateStatus`, // 修改布控状态
  cancelSurveillanceTask: (id) => `${baseUrl}/api/kunlun/event/deployTasks/${id}:cancel`, // 撤销布控任务
  albumList: `${baseUrl}/api/galaxy/v1/album/list`, // 底库列表
  surveillanceNameCheck: `${baseUrl}/api/kunlun/event/deployTasks:repeat`, // 布控任务名称是否重复
  taskDetail: (id) => `${baseUrl}/api/kunlun/event/deployTasks/${id}`, // 布控任务详情
  cameraList: (id) => `${baseUrl}/api/kunlun/event/deployTasks/${id}/camera:list`, // 布控任务详情-相机列表查询
  createTask: `${baseUrl}/api/kunlun/event/deployTasks`, // 新建布控任务
  editTask: (id) => `${baseUrl}/api/kunlun/event/deployTasks/${id}`, // 修改布控任务
  createDeployType: `${baseUrl}/api/kunlun/event/deployTypes`, // 新建布控类型
  deployTypeNameCheck: `${baseUrl}/api/kunlun/event/deployTypes:repeat`, // 检查布控类型名称是否重复
  categoriesList: `${baseUrl}/api/kunlun/event/historyAlarms/data:groupDeploy`, // 查询聚类
  alarmList: `${baseUrl}/api/kunlun/event/historyAlarms/data:list`, // 查询列表
  exportHistory: `${baseUrl}/api/kunlun/event/historyAlarms/data:export`, // 导出数据
  addTemporaries: `${baseUrl}/api/kunlun/event/temporaries:add`, // 添加到暂存架
  deleteTemporaries: `${baseUrl}/api/kunlun/event/temporaries:delete`, // 移出暂存架
  deptTree: `${galaxy}/api/galaxy/v1/auth/organizations/queryTree`, // 部门树
  userTree: `${galaxy}/api/galaxy/v1/auth/organizations/queryOrgTreeAndUser`, // 部门树
  albumListSpecial: `${galaxy}/api/kunlun/event/historyAlarms/albums`, // 查询历史任务的底库
};

// service methods
const SurveillanceTaskSvr = {
  /**
   * 获取布控任务列表
   */
  getSurveillanceTaskList(params = {}) {
    return MegHttp.httpPost(urls.surveillanceTaskList, params);
  },
  getDeployTypeList(params = {}) {
    return MegHttp.httpGet(urls.deployType, params);
  },
  getDeptTree(params = {}) {
    return MegHttp.httpGet(urls.deptTree, params);
  },
  getUserTree(params = {}) {
    return MegHttp.httpGet(urls.userTree, params);
  },
  getCameraAlbum(params = {}) {
    return MegHttp.httpPost(urls.cameraAlbum, params);
  },
  updateStatus(params = {}) {
    return MegHttp.httpPost(urls.updateStatus(params.id), params);
  },
  cancelSurveillanceTask(params = {}) {
    return MegHttp.httpPost(urls.cancelSurveillanceTask(params.id), params);
  },
  getAlbumList(params = {}) {
    return MegHttp.httpPost(urls.albumList, params);
  },
  getAlbumListSpecial(params = {}) {
    return MegHttp.httpPost(urls.albumListSpecial, params);
  },
  checkSurveillanceTaskName(params = {}) {
    return MegHttp.httpPost(urls.surveillanceNameCheck, params);
  },
  getTaskDetail(params = {}) {
    return MegHttp.httpGet(urls.taskDetail(params.id), params);
  },
  getCameraList(params = {}) {
    return MegHttp.httpPost(urls.cameraList(params.id), { pageSize: params.pageSize, pageNo: params.pageNo });
  },
  createTask(params = {}) {
    return MegHttp.httpPost(urls.createTask, params);
  },
  editTask(params = {}) {
    return MegHttp.httpPatch(urls.editTask(params.id), params);
  },
  createDeployType(params = {}) {
    return MegHttp.httpPost(urls.createDeployType, params);
  },
  deployTypeNameCheck(params = {}) {
    return MegHttp.httpPost(urls.deployTypeNameCheck, params);
  },
  getClusterList(params = {}) {
    return MegHttp.httpPost(urls.categoriesList, params);
  },
  getAlarmList(params = {}) {
    return MegHttp.httpPost(urls.alarmList, params);
  },
  exportHistory(params = {}) {
    return MegHttp.httpPost(urls.exportHistory, params);
  },
  addTemporaries(params = {}) {
    return MegHttp.httpPost(urls.addTemporaries, params);
  },
  deleteTemporaries(params = {}) {
    return MegHttp.httpPost(urls.deleteTemporaries, params);
  },
  // old

  /**
   * 获取权限
   */
  auth(request = {}) {
    return MegHttp.httpPost(urls.auth, request);
  }
};

export default SurveillanceTaskSvr;
