/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
const authUrl = config.apiPath.auth; // auth地址
const albumUrl = config.apiPath.galaxyAlbum; // 中台底库地址

// service path
const urls = {
  'analyze': `${baseUrl}/api/compare/v5/analyze`, // 多人脸识别
  'albumList': `${albumUrl}/api/galaxy/v1/album/list`, // 获取底库选择列表
  'cameraList': `${baseUrl}/api/picture/v5/camera/choose/list`, // 获取底库选择列表
  'operateList': `${baseUrl}/api/picture/v5/album/list/operatable`, // 获取可操作的布控库列表
  'passBySearch': `${baseUrl}/api/compare/v5/passBySearch`, // 检索详情比对1：3
  'singleSearch': `${baseUrl}/api/compare/v5/monitorSearch`, // 功能同单人检索但不记录日志
  'monitor': `${baseUrl}/api/galaxy/v1/album/photo:oneClickMonitor`, // 一键布控
  'captureDetail': `${baseUrl}/api/capture/v5/capture/details`, // 抓拍详情
  'searchByPhotos': `${baseUrl}/api/capture/v5/capture/list/byPhotos`, // 以图搜图
  'getRecentPhotos': `${baseUrl}/api/galaxy/v1/recent/recentPhotos`, // 获取最近上传的图片列表
  'getAuth': `${authUrl}/api/auth/v5/permission`,
  'export': `${baseUrl}/api/judge/v5/regionCollision/export`

};

// service methods
const CommonSrv = {
  /**
   * 多人脸识别
   */
  getAnalyze(params = {}) {
    return MegHttp.httpPost(urls.analyze, params);
  },
  /**
  * 获取底库选择列表
  */
  albumList(params = {}) {
    return MegHttp.httpPost(urls.albumList, params);
  },
  /**
  * 获取相机选择列表
  */
  cameraList(params = {}) {
    return MegHttp.httpPost(urls.cameraList, params);
  },
  /**
   * 获取可操作的布控库列表
   */
  operateList(params = {}) {
    return MegHttp.httpPost(urls.operateList, params);
  },
  /**
  * 单人检索
  */
  singleSearch(params = {}) {
    return MegHttp.httpPost(urls.singleSearch, params);
  },
  /**
  * 检索详情比对1：3
  */
  passBySearch(params = {}) {
    return MegHttp.httpPost(urls.passBySearch, params);
  },
  /**
  * 一键布控
  */
  monitor(params = {}) {
    return MegHttp.httpPost(urls.monitor, params);
  },
  /**
  * 抓拍详情
  */
  captureDetail(params = {}) {
    return MegHttp.httpPost(urls.captureDetail, params);
  },
  /**
   * 以图搜图
   */
  searchByPhotos(params = {}) {
    return MegHttp.httpPost(urls.searchByPhotos, params);
  },
  /**
 * 获取最近上传的图片列表
 */
  getRecentPhotos(params = {}) {
    return MegHttp.httpGet(urls.getRecentPhotos, params);
  },
  getAuth(params = {}) {
    return MegHttp.httpPost(urls.getAuth, params);
  },
  /**
   * 导出
   */
  export(params = {}) {
    return MegHttp.httpPost(urls.export, params);
  },
};

export default CommonSrv;
