/* Automatically generated by './build/add-module.js' */
export default {
  lang: 'zh-CN',
  messages: {
    '{entity}不能为空': '{entity}不能为空',
    '{entity}已存在': '{entity}已存在',
    '战法标签': '战法标签',
    '请输入{from}-{to}个汉字，字母，数字': '请输入{from}-{to}个汉字，字母，数字',
    '请输入{from}-{to}个字符': '请输入{from}-{to}个字符'
  }
};
