/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/face-compare/pages/face-compare';
import routes from '@/modules/face-compare/face-compare.router.js';
import store from '@/modules/face-compare/store';

export default {
  module,
  routes,
  store: { faceCompare: store }
};
