/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.galaxyService; // 基础地址
// const auth = config.apiPath.auth; // auth地址

// service path
const urls = {
  verifyFaceToFace: `${baseUrl}/api/galaxy/v1/album/verifyFaceToFace`, // 照片比对
  verifyFaceToIdCard: `${baseUrl}/api/galaxy/v1/album/verifyFaceToIdCard`, // 身份证比对
  operationLog: `${baseUrl}/api/galaxy/v1/operationLog/get` // 检索日志条件查询
};

// service methods
const faceCompareSrv = {
  // 照片比对
  getVerifyFaceToFace(params = {}) {
    return MegHttp.httpPost(urls.verifyFaceToFace, params);
  },
  // 身份证比对
  getVerifyFaceToIdCard(params = {}) {
    return MegHttp.httpPost(urls.verifyFaceToIdCard, params);
  },
  // 检索日志条件查询
  getOperationLog(params = {}) {
    return MegHttp.httpGet(urls.operationLog, params);
  },
};

export default faceCompareSrv;
