/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/text-search/pages/text-search';
import routes from '@/modules/text-search/text-search.router.js';
import store from '@/modules/text-search/store';

export default {
  module,
  routes,
  store: { textSearch: store }
};
