/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service;
// service path
const urls = {
  surveillanceTaskList: `${baseUrl}/api/kunlun/event/deployTasks:search`, // 布控任务列表

  surveillanceNameCheck: `${baseUrl}/api/kunlun/event/deployTasks:repeat`, // 布控任务名称是否重复
  taskDetail: (id) => `${baseUrl}/api/kunlun/event/deployTasks/${id}`, // 布控任务详情

  createTask: `${baseUrl}/api/kunlun/event/cascade/deployTasks`, // 新建布控任务
  editTask: (id) => `${baseUrl}/api/kunlun/event/cascade/deployTasks/${id}`, // 修改布控任务
  updateStatus: (id) => `${baseUrl}/api/kunlun/event/cascade/deployTasks/${id}:updateStatus`, // 修改布控状态
  cancelSurveillanceTask: (id) => `${baseUrl}/api/kunlun/event/cascade/deployTasks/${id}:cancel`, // 撤销布控任务

  deployTypeNameCheck: `${baseUrl}/api/kunlun/event/deployTypes:repeat`, // 检查布控类型名称是否重复
  categoriesList: `${baseUrl}/api/kunlun/event/historyAlarms/data:groupDeploy`, // 查询聚类
  alarmList: `${baseUrl}/api/kunlun/event/historyAlarms/data:list`, // 查询列表
  exportHistory: `${baseUrl}/api/kunlun/event/historyAlarms/data:export`, // 导出数据
  cascadeList: `${baseUrl}/api/face/v6/cascade/registry/getNodeTree`, // 级联布控单位
  albumList: `${baseUrl}/api/galaxy/v1/album/cascade/choose/list`, // 查询底库列表
};

// service methods
const SurveillanceTaskSvr = {
  getCascadeList(request = {}) {
    return MegHttp.httpGet(urls.cascadeList, request);
  },
  getAlbumList(params = {}) {
    return MegHttp.httpPost(urls.albumList, params);
  },
  getSurveillanceTaskList(params = {}) {
    return MegHttp.httpPost(urls.surveillanceTaskList, params);
  },
  updateStatus(params = {}) {
    return MegHttp.httpPost(urls.updateStatus(params.id), params);
  },
  cancelSurveillanceTask(params = {}) {
    return MegHttp.httpPost(urls.cancelSurveillanceTask(params.id), params);
  },
  checkSurveillanceTaskName(params = {}) {
    return MegHttp.httpPost(urls.surveillanceNameCheck, params);
  },
  getTaskDetail(params = {}) {
    return MegHttp.httpGet(urls.taskDetail(params.id), params);
  },
  createTask(params = {}) {
    return MegHttp.httpPost(urls.createTask, params);
  },
  editTask(params = {}) {
    return MegHttp.httpPatch(urls.editTask(params.id), params);
  },
  createDeployType(params = {}) {
    return MegHttp.httpPost(urls.createDeployType, params);
  },
  deployTypeNameCheck(params = {}) {
    return MegHttp.httpPost(urls.deployTypeNameCheck, params);
  },
  getClusterList(params = {}) {
    return MegHttp.httpPost(urls.categoriesList, params);
  },
  getAlarmList(params = {}) {
    return MegHttp.httpPost(urls.alarmList, params);
  },
  exportHistory(params = {}) {
    return MegHttp.httpPost(urls.exportHistory, params);
  },
  // old

  /**
   * 获取权限
   */
  auth(request = {}) {
    return MegHttp.httpPost(urls.auth, request);
  }
};

export default SurveillanceTaskSvr;
