/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/cascade-surveillance-task/pages/cascade-surveillance-task';
import routes from '@/modules/cascade-surveillance-task/cascade-surveillance-task.router.js';
import store from '@/modules/cascade-surveillance-task/store';

export default {
  module,
  routes,
  store: {
    cascadeSurveillanceTask: store
  }
};
