/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/portrait-search/pages/portrait-search';
import routes from '@/modules/portrait-search/portrait-search.router.js';
import store from '@/modules/portrait-search/store';

export default {
  module,
  routes,
  store: { portraitSearch: store }
};
