/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/events-manage/pages/events-manage';
import routes from '@/modules/events-manage/events-manage.router.js';
import store from '@/modules/events-manage/store';

export default {
  module,
  routes,
  store: { eventsManage: store }
};
