/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/cascade-manage/pages/cascade-manage';
import routes from '@/modules/cascade-manage/cascade-manage.router.js';
import store from '@/modules/cascade-manage/store';

export default {
  module,
  routes,
  store: { cascadeManage: store }
};
