/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/workload-statistics/pages/workload-statistics';
import routes from '@/modules/workload-statistics/workload-statistics.router.js';
import store from '@/modules/workload-statistics/store';

export default {
  module,
  routes,
  store: { workloadStatistics: store }
};
