/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
const galaxy = config.apiPath.galaxyService; // auth地址

// service path
const urls = {
  work: `${baseUrl}/api/kunlun/statistic/work/warning`,
  personTree: `${galaxy}/api/galaxy/v1/auth/organizations/queryOrgTree`, // 人员树
  deptTree: `${galaxy}/api/galaxy/v1/auth/organizations/queryTree`, // 部门树
  export: `${baseUrl}/api/kunlun/statistic/work/exportWork`
};

// service methods
const workloadStatisticsSrv = {
  getWorkExport(params) {
    return MegHttp.httpPost(urls.export, params);
  },
  getDashboardData(params) {
    return MegHttp.httpPost(urls.work, params, {
      transformParams: false
    });
  },
  getPersonTree(params = {}) {
    return MegHttp.httpGet(urls.personTree, params);
  },
  getDeptTree(params = {}) {
    return MegHttp.httpGet(urls.deptTree, params);
  },
};

export default workloadStatisticsSrv;
