/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service;
const galaxyUrl = config.apiPath.galaxyService; // 基础地址
// const authUrl = window.config.globalConfig.apiPath.auth;
// const testUrl = 'http://api-insight.cbg.megvii-inc.com/mock/155';

// service path
const urls = {
  getPlanListForScene: `${galaxyUrl}/api/galaxy/v1/device/plans`, // 获取重点单位对应的平面图列表
  analysisCameraList: `${baseUrl}/api/kunlun/analysis/realtime/cameras`, // 查询解析相机列表
  deployCameraList: `${baseUrl}/api/kunlun/event/cameras`, // 查询布控相机列表
  labels: `${galaxyUrl}/api/galaxy/v1/device/cameras:labels`, // 查询相机标签
  places: `${galaxyUrl}/api/galaxy/v1/device/places/listAll`, // 查询相机区域
  keyUnits: `${galaxyUrl}/api/galaxy/v1/device/cameras:units`, // 查询重点单位
  captureCount: `${galaxyUrl}/api/galaxy/v1/capture/dashboard/count`, // 查询抓拍数
  cameraInfo: `${galaxyUrl}/api/galaxy/v1/device/cameras/`, // 获取今日抓拍总数和最近的抓拍信息
  cameraDetail: `${baseUrl}/api/kunlun/analysis/realtime/cameras/`,
  cameraVideo: `${galaxyUrl}/api/galaxy/v1/device/cameras:searchOpenVideoInfo`, // 获取相机视频流地址
  iotUrl: `${galaxyUrl}/api/gmp/v1/stream/getAddr`, // 请求开流websocket地址
};

const MegMapSrv = {
  /**
   * 查询解析状态相机列表
   */
  getAnalysisCameraList(request = {}) {
    return MegHttp.httpPost(`${urls.analysisCameraList}`, request);
  },
  /**
   * 查询布控相机列表
   * @param {Object} request
   */
  getDeployCameraList(request = {}) {
    return MegHttp.httpPost(`${urls.deployCameraList}`, request);
  },
  /**
   * 获取场景的平面图列表
   * @param {Object} request
   */
  getPlanListForScene(request = {}) {
    return MegHttp.httpGet(`${urls.getPlanListForScene}/${request.id}/units`);
  },
  /**
   * 查询抓拍数
   */
  getCaptureCount(request = {}) {
    return MegHttp.httpPost(urls.captureCount, request);
  },
  /**
  * 查询相机详情
  */
  getCameraInfo(request = {}) {
    return MegHttp.httpPost(urls.cameraInfo + request.id, request);
  },
  /**
  * 查询相机视频流地址
  */
  getCameraVideo(request = {}) {
    return MegHttp.httpGet(urls.cameraVideo, request);
  },
  /**
* 查询相机视频流地址
*/
  getIotUrl(request = {}) {
    return MegHttp.httpPost(urls.iotUrl, request);
  },
  /**
   * 查询相机状态
   */
  getCameraDetail(request = {}) {
    return MegHttp.httpGet(urls.cameraDetail + request.id);
  },
  /**
  * 查询相机标签
  */
  getLabels(request = {}) {
    return MegHttp.httpGet(urls.labels, request);
  },
  /**
* 查询相机区域
*/
  getPlaces(request = {}) {
    return MegHttp.httpGet(urls.places, request);
  },
  /**
* 查询重点单位
*/
  getKeyUnits(request = {}) {
    return MegHttp.httpGet(urls.keyUnits, request);
  },
};

export default MegMapSrv;
