/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/attribute-search/pages/attribute-search';
import routes from '@/modules/attribute-search/attribute-search.router.js';
import store from '@/modules/attribute-search/store';

export default {
  module,
  routes,
  store: { attributeSearch: store }
};
