/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
// const baseUrl = config.apiPath.service; // 基础地址
// const auth = config.apiPath.auth; // auth地址
const galaxyUrl = config.apiPath.galaxyService; // 中台服务地址

// service path
const urls = {
  'queryItemOrgTree': `${galaxyUrl}/api/galaxy/v1/auth/organizations/queryTree`, // 获取部门树
  'getLabelList': `${galaxyUrl}/api/galaxy/v1/device/cameras:labels`, // 获取标签树
  'getPlaceList': `${galaxyUrl}/api/galaxy/v1/device/places/listAll`, // 获取归属区域列表
  'getKeyUnitList': `${galaxyUrl}/api/galaxy/v1/device/cameras:units`, // 获取重点单位列表
  'groupsTree': `${galaxyUrl}/api/galaxy/v1/device/cameras/tags:search`, // 自定义分组列表
  'cameraList': `${galaxyUrl}/api/galaxy/v1/device/cameras:search`, // 获取相机列表
  'batchSaveSync': `${galaxyUrl}/api/galaxy/v1/device/cameras:batchSaveSync`, // 启用相机
  'batchSave': `${galaxyUrl}/api/galaxy/v1/device/cameras:batchSave`, // 启用相机
  'batchDelete': `${galaxyUrl}/api/galaxy/v1/device/cameras:batchDelete`, // 停用相机
  'batchDeleteAsync': `${galaxyUrl}/api/galaxy/v1/device/cameras:batchDeleteAsync`, // 停用相机
  'queryCameraDetail': (id) => `${galaxyUrl}/api/galaxy/v1/device/cameras/${id}`, // 查询相机详情
  'deleteCamera': `${galaxyUrl}/api/galaxy/v1/device/cameras:searchDelete`, // 删除相机
  'batchDeleteCamera': `${galaxyUrl}/api/galaxy/v1/device/cameras:searchDelete`, // 删除相机
  'createGroup': `${galaxyUrl}/api/galaxy/v1/device/cameras/tags`, // 新建分组
  'modifyGroup': `${galaxyUrl}/api/galaxy/v1/device/cameras/tags`, // 编辑分组
  'deleteGroup': (id) => `${galaxyUrl}/api/galaxy/v1/device/cameras/tags/${id}`, // 删除分组
  'getGroupById': (id) => `${galaxyUrl}/api/galaxy/v1/device/cameras/tags/${id}`, // 根据id获取分组
  'cameraTree': `${galaxyUrl}/api/galaxy/v1/device/cameras/tree`, // 部门区域相机树
  'exportCamera': `${galaxyUrl}/api/galaxy/v1/device/cameras:searchExport`, // 批量导出相机
  'createCamera': `${galaxyUrl}/api/galaxy/v1/device/cameras:create`, // 新建相机
  'queryBoxTree': `${galaxyUrl}/api/rainbow/v1/device/box/tree`,
  'editCamera': `${galaxyUrl}/api/galaxy/v1/device/cameras:update`, // 编辑相机
  'editApi': '/api/galaxy/v1/device/cameras:batchEdit', // 批量编辑接口地址
  'importApi': '/api/galaxy/v1/device/cameras:batchImport', // 批量导入接口地址
  'downloadTemplate': `${galaxyUrl}/api/galaxy/v1/device/cameras:templateUri`, // 导入相机-下载模板
  'patchUpdateAsync': `${galaxyUrl}/api/galaxy/v1/device/cameras:patchUpdateAsync`, // 批量字段变更
  'allCameraList': `${galaxyUrl}/api/rainbow/v1/device/cameras:searchAll`, // 定制的全量相机获取接口 解决大数据量返回慢的问题
  'calculateCameraSpace': (id) => `${galaxyUrl}/api/rainbow/v1/device/cameras/space/calculate/${id}`, // 计算小时空
  'saveCameraSpace': (id) => `${galaxyUrl}/api/rainbow/v1/device/cameras/space/${id}`, // 保存相机小时空编辑结果
  'searchSpace': (id) => `${galaxyUrl}/api/rainbow/v1/device/cameras/space/${id}`, // 查询小时空
  'queryBoxDetail': `${galaxyUrl}/api/rainbow/v1/device/box`, // 盒子详情
  // 新建相机校验
  'checkCameraExist': `${galaxyUrl}/api/rainbow/v1/device/cameras:checkName`, // 检测相机重名
  'checkChannelExists': `${galaxyUrl}/api/rainbow/v1/device/cameras:checkBoxChannel`, // 校验通道号是否被占用
};

// service methods
const CameraManageSrv = {
  // 获取部门树
  getQueryItemOrgTree(params = {}) {
    return MegHttp.httpGet(urls.queryItemOrgTree, params);
  },
  // 获取标签树
  getLabelList(params = {}) {
    return MegHttp.httpGet(urls.getLabelList, params);
  },
  // 获取归属区域列表
  getPlaceList(params = {}) {
    return MegHttp.httpGet(urls.getPlaceList, params);
  },
  // 获取重点单位列表
  getKeyUnitList(params = {}) {
    return MegHttp.httpGet(urls.getKeyUnitList, params);
  },
  // 分组列表
  getGroupsList(params = {}) {
    return MegHttp.httpGet(urls.groupsTree, params);
  },
  // 获取相机列表
  getCameraList(params = {}) {
    return MegHttp.httpPost(urls.cameraList, params);
  },
  // 获取相机树
  getCameraTree(params = {}) {
    return MegHttp.httpPost(urls.cameraTree, params);
  },
  // 激活相机
  batchSaveSync(params = {}) {
    return MegHttp.httpPatch(urls.batchSaveSync, params);
  },
  // 激活相机
  batchSave(params = {}) {
    return MegHttp.httpPatch(urls.batchSave, params);
  },
  // 停用相机
  batchDelete(params = {}) {
    return MegHttp.httpPost(urls.batchDelete, params);
  },
  // 停用相机
  batchDeleteAsync(params = {}) {
    return MegHttp.httpPost(urls.batchDeleteAsync, params);
  },
  // 查询相机详情
  queryCameraDetail(params = {}) {
    return MegHttp.httpPost(urls.queryCameraDetail(params.id), params);
  },
  // 删除相机
  deleteCamera(params = {}) {
    return MegHttp.httpPost(urls.batchDeleteCamera, params);
  },
  // 删除相机
  batchDeleteCamera(params = {}) {
    return MegHttp.httpPost(urls.batchDeleteCamera, params);
  },
  // 新建分组
  createGroup(params = {}) {
    return MegHttp.httpPost(urls.createGroup, params);
  },
  // 删除分组
  deleteGroup(params = {}) {
    return MegHttp.httpDelete(urls.deleteGroup(params.id));
  },
  // 编辑分组
  modifyGroup(params = {}) {
    return MegHttp.httpPut(urls.modifyGroup, params);
  },
  // 根据id获取分组
  getGroupById(params = {}) {
    return MegHttp.httpGet(urls.getGroupById(params.id));
  },
  // 导出
  exportCamera(params = {}) {
    return MegHttp.httpPost(urls.exportCamera, params);
  },
  // 新建相机
  createCamera(params = {}) {
    return MegHttp.httpPost(urls.createCamera, params);
  },
  // 新建相机查询关联智能盒
  queryBoxTree(params = {}) {
    return MegHttp.httpGet(urls.queryBoxTree, params);
  },
  editApi() {
    return urls.editApi;
  },
  importApi() {
    return urls.importApi;
  },
  // 下载相机导入模板
  getDownloadTemplate(params = {}) {
    return MegHttp.httpPost(urls.downloadTemplate, params);
  },
  // 批量字段变更
  patchUpdateAsync(params = {}) {
    return MegHttp.httpPost(urls.patchUpdateAsync, params, { transformParams: false });
  },
  // 获取相机列表
  geAlltCameraList(params = {}) {
    return MegHttp.httpPost(urls.allCameraList, params);
  },
  // 计算小时空
  calculateCameraSpace(params = {}) {
    return MegHttp.httpPost(`${urls.calculateCameraSpace(params.id)}`, params);
  },
  // 标记小时空
  saveCameraSpace(params = {}) {
    return MegHttp.httpPut(`${urls.saveCameraSpace(params.id)}`, params);
  },
  // 查询小时空
  searchSpace(params = {}) {
    return MegHttp.httpGet(`${urls.searchSpace(params.id)}`, params);
  },
  // 盒子详情
  queryBoxDetail(params = {}) {
    return MegHttp.httpGet(`${urls.queryBoxDetail}/${params.id}`, params);
  },

  checkCameraExist(params = {}) {
    return MegHttp.httpPost(urls.checkCameraExist, params);
  },
  checkChannelExists(params = {}) {
    return MegHttp.httpPost(urls.checkChannelExists, params);
  },
  // 编辑相机
  setEditCamera(params = {}) {
    return MegHttp.httpPatch(urls.editCamera, params, {
      transformParams: [],
    });
  },
};

export default CameraManageSrv;
