/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/camera-manage/pages/camera-manage';
import routes from '@/modules/camera-manage/camera-manage.router.js';
import store from '@/modules/camera-manage/store';

export default {
  module,
  routes,
  store: { cameraManage: store }
};
