/* Automatically generated by './build/add-module.js' */
const actions = {
  manageShelf({ commit }, state) {
    commit('MANAGE_SHELF', state);
  },
  setShelfState({ commit }, state) {
    commit('SET_SHELF_STATE', state);
  },
  addToEvent({ commit }, state) {
    commit('ADD_TO_EVENT', state);
  },
  deleteShelf({ commit }, state) {
    commit('DELETE_SHELF', state);
  }
};

export default actions;
