/* Automatically generated by './build/add-module.js' */
const getters = {
  isShelfOpen(state) {
    return state.isShelfOpen;
  },
  manageShelfData(state) {
    return state.manageShelfData;
  },
  eventAddData(state) {
    return state.eventAddData;
  },
  deleteShelfData(state) {
    return state.deleteShelfData;
  },
};

export default getters;
