/* Automatically generated by './build/add-module.js' */
const mutations = {
  /*
  * 更新暂存架打开状态
  * @param {isOpen: Boolean}
  * @return
  * */
  SET_SHELF_STATE(state, isOpen) {
    state.isShelfOpen = isOpen;
  },
  /*
  * 添加到暂存架事件
  * @param {any}
  * @return
  * */
  MANAGE_SHELF(state, data) {
    state.manageShelfData = data;
  },
  /*
  * 添加到事件
  * @param {any}
  * @return
  * */
  ADD_TO_EVENT(state) {
    state.eventAddData += 1;
  },
  /*
  * 添加到事件
  * @param {any}
  * @return
  * */
  DELETE_SHELF(state, data) {
    state.deleteShelfData = data;
  },
};

export default mutations;
