/* Automatically generated by './build/add-module.js' */
import actions from './actions';
import mutations from './mutations';
import getters from './getters';

const textSearch = {
  namespaced: true,
  mutations,
  actions,
  getters,
  state: {},
};

export default textSearch;
