/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service;
// const authUrl = window.config.globalConfig.apiPath.auth;
// const testUrl = 'http://api-insight.cbg.megvii-inc.com/mock/155';

// service path
const urls = {
  'searchByPhotos': `${baseUrl}/api/galaxy/v1/capture/allInOne/queryCapture`, // 以图搜图
};

const AnalysisFilterSrv = {
  /**
   * 以图搜图
   */
  searchByPhotos(params = {}) {
    return MegHttp.httpPost(urls.searchByPhotos, params);
  },
};
export default AnalysisFilterSrv;
