/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/judge-after/pages/judge-after';
import routes from '@/modules/judge-after/judge-after.router.js';
import store from '@/modules/judge-after/store';

export default {
  module,
  routes,
  store: { judgeAfter: store }
};
