/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/record-crash/pages/record-crash';
import routes from '@/modules/record-crash/record-crash.router.js';
import store from '@/modules/record-crash/store';

export default {
  module,
  routes,
  store: { recordCrash: store }
};
