/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/face-identity/pages/face-identity';
import routes from '@/modules/face-identity/face-identity.router.js';
import store from '@/modules/face-identity/store';

export default {
  module,
  routes,
  store: { faceIdentity: store }
};
