/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
const galaxybaseUrl = config.apiPath.galaxyService; // 基础地址
// const auth = config.apiPath.auth; // auth地址

// service path
const urls = {
  getAlbum: `${galaxybaseUrl}/api/galaxy/v1/album/list`, // 获取底库
  search: `${baseUrl}/api/kunlun/search/album`, // 人像检索
  export: `${baseUrl}/api/galaxy/v1/album/exportSearchResult`, // 导出
  operationLog: `${baseUrl}/api/galaxy/v1/operationLog/get`, // 检索日志条件查询
  addTemporarys: `${baseUrl}/api/kunlun/event/temporaries:add`, // 加入暂存架
  delTemporarys: `${baseUrl}/api/kunlun/event/temporaries:delete`, // 移出暂存架

};

// service methods
const faceIdentitySrv = {
  /**
 * 加入暂存架
 */
  addTemporarys(params = {}) {
    return MegHttp.httpPost(urls.addTemporarys, params);
  },
  /**
* 移出暂存架
*/
  delTemporarys(params = {}) {
    return MegHttp.httpPost(urls.delTemporarys, params);
  },
  /**
   * 获取底库
   */
  getAlbum(params = {}) {
    return MegHttp.httpPost(urls.getAlbum, params);
  },
  /**
   * 人像检索
   */
  search(params = {}) {
    return MegHttp.httpPost(urls.search, params);
  },
  /**
   * 导出
   */
  export(params = {}) {
    return MegHttp.httpPost(urls.export, params);
  },
  /**
   * 检索日志条件查询
   */
  getOperationLog(params = {}) {
    return MegHttp.httpGet(urls.operationLog, params);
  },
};

export default faceIdentitySrv;
