/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/track-analysis/pages/track-analysis';
import routes from '@/modules/track-analysis/track-analysis.router.js';
import store from '@/modules/track-analysis/store';

export default {
  module,
  routes,
  store: { trackAnalysis: store }
};
