/* Automatically generated by './build/add-module.js' */
/* 发布集成环境下 router-view 不同 */
// eslint-disable-next-line consistent-return
export default [{
  children: [
    {
      path: 'analysis-result',
      name: 'analysis-result',
      component: () => import(/* webpackChunkName: "track-analysis" */'./pages/analysis-result')
    }
  ]
}];
