/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址

// service path
const urls = {
  'regionList': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/list`, // 任务列表
  'regionStatistics': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/countByStatus`, // 任务状态统计
  'groupCount': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/result/groupCount`, // 任务分类统计
  'groupResult': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/result`, // 任务分类结果
  'taskDetail': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/detail/`, // 任务详情信息
  'cameraList': `${baseUrl}/api/galaxy/v1/device/tree`, // 获取有权限的相机列表
  'addTask': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/add`, // 添加任务
  'deleteTask': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/delete/`, // 删除任务
  'deleteResult': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/delResult`, // 删除单个结果
  'cardDetail': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/result/detail/`, // 碰撞结果详情
  'taskName': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/nameExist/`, // 人物名是否存在
  'threshold': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/threshold`, // 获取推荐阈值
  'terminateTask': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/terminate/`, // 终止任务
  'restartTask': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/restart/`, // 重新开始任务
  'modifyJobName': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/modifyJobName/`, // 修改任务名
  'export': `${baseUrl}/api/kunlun/judge/regionAlbumCollision/export`, // 导出
  'getAlbum': `${baseUrl}/api/galaxy/v1/album/list`,
  emitRemoteFullImage: `${baseUrl}/api/kunlun/search/capture/full`, // 触发设置远程拉取全景图
  'analyze': `${baseUrl}/api/compare/v5/analyze`, // 多人脸识别
};

// service methods
const AlbumRegionSrv = {
  /**
  * 新建任务
  */
  addTask(params = {}) {
    return MegHttp.httpPost(urls.addTask, params);
  },
  // 删除任务
  deleteTask(params = '') {
    return MegHttp.httpPost(urls.deleteTask + params);
  },
  // 删除单个结果
  deleteResult(params = {}) {
    return MegHttp.httpGet(urls.deleteResult, params);
  },
  // 频繁出没列表
  getRegionList(params = {}) {
    return MegHttp.httpGet(urls.regionList, params);
  },
  // 进度统计
  regionStatistics(params = {}) {
    return MegHttp.httpGet(urls.regionStatistics, params);
  },
  // 分类统计
  groupCount(params = {}) {
    return MegHttp.httpPost(urls.groupCount, params);
  },
  // 分类结果
  groupResult(params = {}) {
    return MegHttp.httpPost(urls.groupResult, params);
  },
  // 任务详情
  taskDetail(params = '') {
    return MegHttp.httpGet(urls.taskDetail + params);
  },
  // 任务人员出现记录
  personResult(params = {}) {
    return MegHttp.httpGet(urls.personResult + params.personId, { groupType: params.groupType });
  },
  /**
    * 获取有权限的相机列表
     */
  cameraList(params = {}) {
    return MegHttp.httpPost(urls.cameraList, params);
  },
  /**
    * 碰撞结果详情
    */
  cardDetail(params = '') {
    return MegHttp.httpGet(urls.cardDetail + params);
  },
  // 任务详情
  jobDetail(params = '') {
    return MegHttp.httpGet(urls.taskDetail + params);
  },
  // 任务名是否存在
  taskName(params = {}) {
    return MegHttp.httpGet(urls.taskName, params);
  },
  threshold(params = {}) {
    return MegHttp.httpGet(urls.threshold, params);
  },
  terminateTask(params = '') {
    return MegHttp.httpGet(urls.terminateTask + params);
  },
  restartTask(params = '') {
    return MegHttp.httpGet(urls.restartTask + params);
  },
  // 修改任务名
  modifyJobName(params = {}) {
    return MegHttp.httpPost(urls.modifyJobName + params.id, { jobName: params.jobName });
  },
  // 导出
  export(params = {}) {
    return MegHttp.httpPost(urls.export, params);
  },
  getAlbum(params = {}) {
    return MegHttp.httpPost(urls.getAlbum, params);
  },
  /**
   * 触发获取远程全景图
   */
  emitRemoteFullImage(request = {}) {
    return MegHttp.httpGet(urls.emitRemoteFullImage, request);
  },
  /**
   * 多人脸识别
   */
  getAnalyze(params = {}) {
    return MegHttp.httpPost(urls.analyze, params);
  },
};

export default AlbumRegionSrv;
