/* Automatically generated by './build/add-module.js' */
/* 发布集成环境下 router-view 不同 */
// eslint-disable-next-line consistent-return
export default [{
  children: [
    {
      path: 'album-results',
      name: 'album-results',
      component: () => import(/* webpackChunkName: "albumResults" */'./pages/album-results')
    }
  ]
}];
