/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/album-region/pages/album-region';
import routes from '@/modules/album-region/album-region.router.js';
import store from '@/modules/album-region/store';

export default {
  module,
  routes,
  store: { albumRegion: store }
};
