/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/track/pages/track';
import routes from '@/modules/track/track.router.js';
import store from '@/modules/track/store';

export default {
  module,
  routes,
  store: { track: store }
};
