/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// MegHttp from insight-utils, MegHttp.httpGet or MegHttp.httpPost

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const auth = window.config.globalConfig.apiPath.auth; // auth地址

// service path
const urls = {
  'getTrack': `${baseUrl}/api/kunlun/judge/track`,
  'searchByPhotos': `${baseUrl}/api/kunlun/search/capture/allInOne/queryCaptureResult`, // 以图搜图
  'export': `${baseUrl}/api/kunlun/judge/track/export`, // 导出
};

// service methods
const TrackSrv = {
  /**
   *  轨迹分析
   */
  getTrack(params = {}) {
    return MegHttp.httpPost(urls.getTrack, params);
  },
  // 导出
  export(params = {}) {
    return MegHttp.httpPost(urls.export, params);
  },
  searchByPhotos(params = {}) {
    return MegHttp.httpPost(urls.searchByPhotos, params);
  },
};

export default TrackSrv;
