/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

const baseUrl = config.apiPath.service;
const galaxyUrl = config.apiPath.galaxyService;

const urls = {
  jumpPicture: `${baseUrl}/api/kunlun/judge/jumpPicture`,
  analyze: `${galaxyUrl}/api/galaxy/v1/system/image/action/image:analyze`, // 多人脸识别
};

const CommonJumpWithImgSrv = {
  /**
  * 携图跳转：获取可操作列表
  */
  getJumpPicture(params = {}) {
    return MegHttp.httpPost(urls.jumpPicture, params);
  },
  analyze(params = {}) {
    return MegHttp.httpPost(urls.analyze, params);
  }
};

export default CommonJumpWithImgSrv;
