/* Automatically generated by './build/add-module.js' */
import actions from './actions';
import mutations from './mutations';
import getters from './getters';

const searchLog = {
  namespaced: true,
  mutations,
  actions,
  getters,
  state: {},
};

export default searchLog;
