/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/human-fusion/pages/human-fusion';
import routes from '@/modules/human-fusion/human-fusion.router.js';
import store from '@/modules/human-fusion/store';

export default {
  module,
  routes,
  store: { humanFusion: store }
};
