/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service;
const authUrl = config.apiPath.galaxyService;
// const testUrl = 'http://api-insight.cbg.megvii-inc.com/mock/155';

// service path
const urls = {
  'analyze': `${baseUrl}/api/galaxy/v1/album/photo:analyze`, // 多人脸识别
  'albumList': `${baseUrl}/api/galaxy/v1/album/list`, // 获取底库选择列表
  'singleSearch': `${baseUrl}/api/compare/v5/search`, // 单人检索
  'monitor': `${baseUrl}/api/alarm/v5/capture/monitor`, // 一键布控
  'getRecentPhotos': `${baseUrl}/api/galaxy/v1/recent/recentPhotos`, // 获取最近上传的图片列表
  'checkDupl': `${baseUrl}/api/auth/v5/check`, // 校验重名
  'queryItemOrgTree': `${authUrl}/api/auth/v5/organizations/queryTree`, // 获取子部门树
};

// service methods
const addphotoSrv = {
  /**
   * 多人脸识别
   */
  getAnalyze(params = {}) {
    return MegHttp.httpPost(urls.analyze, params);
  },
  /**
  * 获取底库选择列表
  */
  albumList(params = {}) {
    return MegHttp.httpPost(urls.albumList, params);
  },

  /**
  * 单人检索
  */
  singleSearch(params = {}) {
    return MegHttp.httpPost(urls.singleSearch, params);
  },
  /**
  * 一键布控
  */
  monitor(params = {}) {
    return MegHttp.httpPost(urls.monitor, params);
  },
  /**
   * 获取最近上传的图片列表
   */
  getRecentPhotos(params = {}) {
    return MegHttp.httpGet(urls.getRecentPhotos, params);
  },
  /**
   * 校验重名
   */
  checkDupl: (params = {}) => MegHttp.httpPost(urls.checkDupl, params),
  /**
   * 子部门树
   */
  getQueryItemOrgTree(params = {}) {
    return MegHttp.httpGet(urls.queryItemOrgTree, params);
  },
};
export default addphotoSrv;
