/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const auth = config.apiPath.auth; // auth地址

// service path
const urls = {
  // 离线任务列表拉取
  'offlineTaskList': `${baseUrl}/api/galaxy/v1/analysis/offline/batchTask:list`,
  // 离线任务文件拉取
  // 'taskFileList': `${baseUrl}/api/galaxy/v1/analysis/offline/resource:list`
  'taskFileList': `${baseUrl}/api/galaxy/v1/analysis/offline/batchTask/item:list`
};

// service methods
const SearchSrv = {
  // 拉取离线任务列表
  fetchOfflineTaskList(params = {}) {
    return MegHttp.httpPost(urls.offlineTaskList, params);
  },
  // 离线任务文件拉取
  fetchOfflineFileList(params = {}) {
    return MegHttp.httpPost(urls.taskFileList, params);
  },
};

export default SearchSrv;
