/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const auth = config.apiPath.auth; // auth地址

// service path
const urls = {
  dashboard: `${baseUrl}/api/kunlun/statistic/album/dashBoard:stat`,
  database: `${baseUrl}/api/galaxy/v1/album/list`,
  export: `${baseUrl}/api/kunlun/statistic/album:export`
};

// service methods
const databaseStatisticsSrv = {
  getDashboardData(params) {
    return MegHttp.httpPost(urls.dashboard, params, {
      transformParams: false
    });
  },
  getDatabaseList(params = {}) {
    return MegHttp.httpPost(urls.database, params);
  },
  getDatabaseExport(params = {}) {
    return MegHttp.httpPost(urls.export, params);
  },
};

export default databaseStatisticsSrv;
