/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/hiding-place/pages/hiding-place';
import routes from '@/modules/hiding-place/hiding-place.router.js';
import store from '@/modules/hiding-place/store';

export default {
  module,
  routes,
  store: { hidingPlace: store }
};
