/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/search-log/pages/search-log';
import routes from '@/modules/search-log/search-log.router.js';
import store from '@/modules/search-log/store';

export default {
  module,
  routes,
  store: { searchLog: store }
};
