/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const galaxyUrl = config.apiPath.galaxyService; // 基础地址（中台2.0）

// service path
const urls = {
  peopleTree: `${galaxyUrl}/api/galaxy/v1/auth/organizations/itemTree`, // 人员树(中台服务)
  queryLogList: `${galaxyUrl}/api/galaxy/v1/operationLog/queryLogList`, // 获取日志分页列表(中台服务)
  countLogByUsers: `${galaxyUrl}/api/galaxy/v1/operationLog/countLogByUsers`, // 按用户统计检索次数(中台服务)
  countLogByDepts: `${galaxyUrl}/api/galaxy/v1/operationLog/countLogByDepts`, // 按部门统计检索次数(中台服务)
};

// service methods
const searchLogSrv = {
  /**
   * 按部门统计检索次数
   */
  countLogByDepts(parmas) {
    return MegHttp.httpPost(urls.countLogByDepts, parmas);
  },
  /**
   * 按用户统计检索次数
   */
  countLogByUsers(parmas) {
    return MegHttp.httpPost(urls.countLogByUsers, parmas);
  },
  /**
   * 获取日志分页列表
   */
  queryLogList(parmas) {
    return MegHttp.httpPost(urls.queryLogList, parmas);
  },
  /**
   * 人员树
   */
  peopleTree(params) {
    return MegHttp.httpGet(urls.peopleTree, params);
  },
};

export default searchLogSrv;
