/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/search-statistics/pages/search-statistics';
import routes from '@/modules/search-statistics/search-statistics.router.js';
import store from '@/modules/search-statistics/store';

export default {
  module,
  routes,
  store: { searchStatistics: store }
};
