/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
const galaxy = config.apiPath.galaxyService; // 中台

// service path
const urls = {
  dashboard: `${baseUrl}/api/kunlun/statistic/search/dashboard:stat`,
  deptTree: `${galaxy}/api/galaxy/v1/auth/organizations/queryTree`, // 部门树
  database: `${baseUrl}/api/galaxy/v1/album/list`,
  export: `${baseUrl}/api/kunlun/statistic/search:export`
};

// service methods
const searchStatisticsSrv = {
  getSearchExport(params) {
    return MegHttp.httpPost(urls.export, params);
  },
  getDashboardData(params) {
    return MegHttp.httpPost(urls.dashboard, params, {
      transformParams: false
    });
  },
  getDeptTree(params = {}) {
    return MegHttp.httpGet(urls.deptTree, params);
  },
  getDatabaseList(params = {}) {
    return MegHttp.httpPost(urls.database, params);
  },
};

export default searchStatisticsSrv;
