/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/person-gather/pages/person-gather';
import routes from '@/modules/person-gather/person-gather.router.js';
import store from '@/modules/person-gather/store';

export default {
  module,
  routes,
  store: { personGather: store }
};
