/* Automatically generated by './build/add-module.js' */
/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const auth = window.config.globalConfig.apiPath.auth; // auth地址

// service path
const urls = {
  'queryGatherList': `${baseUrl}/api/kunlun/judge/personCluster/queryByPage`,
  'queryProgerssStats': `${baseUrl}/api/kunlun/judge/personCluster/progressStatistics`,
  'uploadFile': `${baseUrl}/api/kunlun/judge/personCluster/uploadFile`,
  'queryTaskDetail': `${baseUrl}/api/kunlun/judge/personCluster/detail`,
  'deleteTask': `${baseUrl}/api/kunlun/judge/personCluster/delete`,
  'faceAnalyze': `${baseUrl}/api/compare/v5/analyze`, // 人脸检测
  'restartTask': `${baseUrl}/api/kunlun/judge/personCluster/restart`,
  'createTask': `${baseUrl}/api/kunlun/judge/personCluster/add`,
  'stopTask': `${baseUrl}/api/kunlun/judge/personCluster/terminate`,
  'queryResultList': `${baseUrl}/api/kunlun/judge/personCluster/resultList`,
  'queryPersonList': `${baseUrl}/api/kunlun/judge/personCluster/personResult`,
  'modifyJobName': `${baseUrl}/api/kunlun/judge/personCluster/modifyJobName`,
  'deleteFace': `${baseUrl}/api/kunlun/judge/personCluster/deleteFace`,
  'checkTaskName': `${baseUrl}/api/kunlun/judge/personCluster/nameExist`,
  'export': `${baseUrl}/api/kunlun/judge/personCluster/export`,
  'queryDoneJobVideos': `${baseUrl}/api/kunlun/analysis/offline/listVideoGroupByTask`,
  'resourceList': `${baseUrl}/api/galaxy/v1/analysis/offline/resource:list`
};

// service methods
const PersonGatherSrv = {
  queryGatherList(params = {}) {
    return MegHttp.httpPost(urls.queryGatherList, params);
  },
  queryProgerssStats(params = {}) {
    return MegHttp.httpGet(urls.queryProgerssStats, params);
  },
  uploadFile(params = { }) {
    return MegHttp.httpPost(urls.uploadFile + params);
  },
  queryTaskDetail(params = {}) {
    return MegHttp.httpPost(urls.queryTaskDetail, params);
  },
  deleteTask(params = { }) {
    return MegHttp.httpPost(urls.deleteTask, params);
  },
  restartTask(params = { }) {
    return MegHttp.httpPost(urls.restartTask, params);
  },
  createTask(params = {}) {
    return MegHttp.httpPost(urls.createTask, params);
  },
  stopTask(params = { }) {
    return MegHttp.httpPost(urls.stopTask, params);
  },
  queryResultList(params = { }) {
    return MegHttp.httpPost(urls.queryResultList, params);
  },
  queryPersonList(params = { }) {
    return MegHttp.httpPost(urls.queryPersonList, params);
  },
  modifyJobName(params = {}) {
    return MegHttp.httpPost(urls.modifyJobName, params);
  },
  deleteFace(params = {}) {
    return MegHttp.httpPost(urls.deleteFace, params);
  },
  checkTaskName(params = {}) {
    return MegHttp.httpPost(urls.checkTaskName, params);
  },
  export(params = {}) {
    return MegHttp.httpPost(urls.export, params);
  },
  queryDoneJobVideos(params = {}) {
    return MegHttp.httpGet(urls.queryDoneJobVideos, params);
  },
  // 人脸检测
  faceAnalyze(params = {}) {
    return MegHttp.httpPost(urls.faceAnalyze, params);
  },
  getResourceList(params = {}) {
    return MegHttp.httpPost(urls.resourceList, params);
  }
};

export default PersonGatherSrv;
