/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
// const baseUrl = config.apiPath.service; // 基础地址
// const auth = config.apiPath.auth; // auth地址
const galaxyUrl = config.apiPath.galaxyService; // 中台服务地址

// service path
const urls = {
  systemConfig: `${galaxyUrl}/api/galaxy/v1/system/configuration/map`, // 获取系统配置信息
  updateSystemConfig: `${galaxyUrl}/api/galaxy/v1/system/configuration/update/batch`, // 更新系统配置信息
  getAlbumList: `${galaxyUrl}/api/galaxy/v1/album/list`, // 底库列表
  upload: `${galaxyUrl}/api/galaxy/v1/system/extra/multipartFile/save`, // logo上传
};

// service methods
const baseConfigSrv = {
  upload: urls.upload,
  getSystemConfig(params = {}) {
    return MegHttp.httpGet(urls.systemConfig, params);
  },
  updateSystemConfig(params = {}) {
    return MegHttp.httpPost(urls.updateSystemConfig, params);
  },
  getAlbumList(params = {}) {
    return MegHttp.httpPost(urls.getAlbumList, params);
  }
};

export default baseConfigSrv;
