/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/basic-config/pages/basic-config';
import routes from '@/modules/basic-config/basic-config.router.js';
import store from '@/modules/basic-config/store';

export default {
  module,
  routes,
  store: { baseConfig: store }
};
