/* Automatically generated by './build/add-module.js' */
import './preset';
import module from '@/modules/multi-person/pages/multi-person';
import routes from '@/modules/multi-person/multi-person.router.js';
import store from '@/modules/multi-person/store';

export default {
  module,
  routes,
  store: { multiPerson: store }
};
