/* Automatically generated by './build/add-module.js' */
import MegHttp from 'megvii-http';
import config from '@/utils/config.utils';

// path prefix
const baseUrl = config.apiPath.service; // 基础地址
// const auth = window.config.globalConfig.apiPath.auth; // auth地址

// service path
const urls = {
  'getMultiPersonList': `${baseUrl}/api/kunlun/judge/multiSearch/list`,
  'deleteList': `${baseUrl}/api/kunlun/judge/multiSearch/del`,
  'newPerson': `${baseUrl}/api/kunlun/judge/multiSearch`,
  'uploadFile': `${baseUrl}/api/kunlun/judge/multiSearch/uploadFile`,
  'personDetail': `${baseUrl}/api/kunlun/judge/multiSearch`,
  'personLists': `${baseUrl}/api/kunlun/judge/multiSearch/results`,
  'moreData': `${baseUrl}/api/kunlun/judge/multiSearch/results/info`,
  'personStatistics': `${baseUrl}/api/kunlun/judge/multiSearch/statistics`,
  'personUploadFile': `${baseUrl}/zuul/api/kunlun/judge/multiSearch/uploadFile`,
  'getAlbum': `${baseUrl}/api/galaxy/v1/album/list`,
  'taskName': `${baseUrl}/api/kunlun/judge/multiSearch/nameExist`,
  'personCancel': `${baseUrl}/api/kunlun/judge/multiSearch/terminate/`,
  'restartTask': `${baseUrl}/api/kunlun/judge/multiSearch/restart/`,
  'exportSearchResult': `${baseUrl}/api/kunlun/judge/multiSearch/export`, // 导出
  'modifyJobName': `${baseUrl}/api/kunlun/judge/multiSearch/update/`, // 修改任务名
  'pathLists': `${baseUrl}/api/judge/v5/multipleSingleSearch/directoryList`, // 获取路径列表
  'newAllPerson': `${baseUrl}/api/judge/v5/multipleSingleSearch/searchByFilePath`, // 批量任务
};

// service methods
const MultiPersonSrv = {
  // 多人检索列表
  getMultiPersonList(params = {}) {
    return MegHttp.httpGet(urls.getMultiPersonList, params);
  },
  deleteList(params = {}) {
    return MegHttp.httpPost(`${urls.deleteList}/${params.jobId}`);
  },
  newPerson(params = {}) {
    return MegHttp.httpPost(urls.newPerson, params);
  },
  uploadFile(params = {}) {
    return MegHttp.httpPost(urls.uploadFile, params);
  },
  personDetail(params = {}) {
    return MegHttp.httpGet(`${urls.personDetail}/${params.jobId}`);
  },
  personLists(params = {}) {
    const pams = {
      pageNo: params.params.pageNo,
      pageSize: params.params.pageSize
    };
    return MegHttp.httpGet(`${urls.personLists}/${params.jobId}`, pams);
  },
  moreData(params = {}) {
    const pams = {
      pageNo: params.params.pageNo,
      pageSize: params.params.pageSize
    };
    return MegHttp.httpGet(`${urls.moreData}/${params.photoId}`, pams);
  },
  personStatistics(params = {}) {
    return MegHttp.httpGet(urls.personStatistics, params);
  },
  personUploadFile(params = {}) {
    return MegHttp.httpPost(`${urls.personUploadFile}/${params.jobId}`, params.formData);
  },
  getAlbum(params = {}) {
    return MegHttp.httpPost(urls.getAlbum, params);
  },
  taskName(params = {}) {
    return MegHttp.httpGet(urls.taskName, params);
  },
  personCancel(params = '') {
    return MegHttp.httpGet(urls.personCancel + params);
  },
  restartTask(params = '') {
    return MegHttp.httpGet(urls.restartTask + params);
  },
  exportSearchResult(params = {}) {
    return MegHttp.httpPost(urls.exportSearchResult, params);
  },
  // 修改任务名
  modifyJobName(params = {}, id) {
    return MegHttp.httpPost(urls.modifyJobName + id, params);
  },
  pathLists(params = {}) {
    return MegHttp.httpGet(urls.pathLists, params);
  },
  newAllPerson(params = {}) {
    return MegHttp.httpPost(urls.newAllPerson, params);
  },
};
export default MultiPersonSrv;
