/* Automatically generated by './build/add-module.js' */
/* 发布集成环境下 router-view 不同 */
// eslint-disable-next-line consistent-return
export default [{
  children: [
    {
      path: 'person-lists',
      name: 'person-lists',
      component: () => import(/* webpackChunkName: "personLists" */'./pages/person-lists')
    },
    {
      path: 'more-card',
      name: 'more-card',
      component: () => import(/* webpackChunkName: "moreCard" */'./pages/more-card')
    }
  ]
}];
